# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangedetail',
            name='contract_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='exchangedetail',
            name='currency_pair',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exchangedetail',
            name='exchange_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='exchangedetail',
            name='lot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exchangedetail',
            name='method',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exchangedetail',
            name='settlement_profit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='exchangedetail',
            name='trade_profit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exchangedetail',
            name='trade_section',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exchangedetail',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
