# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20151222_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='kessai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('contract_date', models.DateTimeField(null=True)),
                ('kendama_num', models.IntegerField(null=True)),
                ('currency_pair', models.CharField(max_length=255, null=True)),
                ('trade_method', models.CharField(max_length=255, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('settlement_price', models.FloatField(null=True)),
                ('tatal_sw', models.IntegerField(null=True)),
                ('realized_profit', models.IntegerField(null=True)),
                ('total_loss', models.IntegerField(null=True)),
            ],
        ),
    ]
